const Map<String, Map<String, String>> chuoiVanBan = {
  'vi': {
    'batDau': 'Bắt đầu',
    'tamDung': 'Tạm dừng',
    'datLai': 'Đặt lại',
    'dangTapTrung': 'Đang tập trung',
    'dangNghiNgoi': 'Đang nghỉ ngơi',
    'sanSang': 'Sẵn sàng bắt đầu',
    'nhapThoiGian': 'Nhập thời gian mong muốn',
    'gio': 'Giờ',
    'phut': 'Phút',
    'giay': 'Giây',
    'huy': 'Hủy',
    'xacNhan': 'Xác nhận',
    'cay': 'Cây',

    'thongKe': 'Thống kê',
    'homNay': 'Hôm nay',
    'phien': 'phiên',
    'thoiGian': 'Thời gian',
    'tatCaThoiGian': 'Tất cả thời gian',
    'phutDonVi': 'phút',
    'chucMung': 'Chúc mừng bạn đã tập trung!',

    'caiDat': 'Cài đặt Pomodoro',
    'cauHinhThoiGian': 'Cấu hình thời gian (Phút)',
    'thoiGianTapTrung': 'Thời gian tập trung',
    'thoiGianNghiNgan': 'Thời gian nghỉ ngắn',
    'thoiGianNghiDai': 'Thời gian nghỉ dài',
    'chuKy': 'Chu kỳ',
    'soPhienNghiDai': 'Số phiên để nghỉ dài',
    'luuCaiDat': 'Lưu cài đặt',
    'daLuu': 'Đã lưu cấu hình thành công!',
    'ngonNgu': 'Ngôn ngữ',
    'tiengViet': 'Tiếng Việt',
    'tiengAnh': 'English',

    'cuaHangCay': 'Cửa hàng cây',
    'tongThoiGian': 'Tổng thời gian',
    'chuaMoKhoa': 'Cây này chưa được mở khóa!',
    'canPhut': 'Cần',
    'daMoKhoa': 'Đã mở khóa',
    'dangDung': 'Đang dùng',

    'thongTinNhom': 'Thông tin nhóm',
    'tenNhom': 'Nhóm 8 - LTTBDD N03',
    'thanhVien': 'Thành viên:',
    'mssv': 'MSSV',
  },
  'en': {
    'batDau': 'Start',
    'tamDung': 'Pause',
    'datLai': 'Reset',
    'dangTapTrung': 'Focusing',
    'dangNghiNgoi': 'On break',
    'sanSang': 'Ready to start',
    'nhapThoiGian': 'Enter desired time',
    'gio': 'Hour',
    'phut': 'Minute',
    'giay': 'Second',
    'huy': 'Cancel',
    'xacNhan': 'Confirm',
    'cay': 'Tree',

    'thongKe': 'Statistics',
    'homNay': 'Today',
    'phien': 'session(s)',
    'thoiGian': 'Time',
    'tatCaThoiGian': 'All time',
    'phutDonVi': 'min',
    'chucMung': 'Great job focusing!',

    'caiDat': 'Pomodoro Settings',
    'cauHinhThoiGian': 'Time Configuration (Minutes)',
    'thoiGianTapTrung': 'Focus duration',
    'thoiGianNghiNgan': 'Short break',
    'thoiGianNghiDai': 'Long break',
    'chuKy': 'Cycle',
    'soPhienNghiDai': 'Sessions before long break',
    'luuCaiDat': 'Save settings',
    'daLuu': 'Settings saved successfully!',
    'ngonNgu': 'Language',
    'tiengViet': 'Tiếng Việt',
    'tiengAnh': 'English',

    'cuaHangCay': 'Tree Collection',
    'tongThoiGian': 'Total time',
    'chuaMoKhoa': 'This tree is not unlocked yet!',
    'canPhut': 'Need',
    'daMoKhoa': 'Unlocked',
    'dangDung': 'In use',

    'thongTinNhom': 'Group Info',
    'tenNhom': 'Group 8 - LTTBDD N03',
    'thanhVien': 'Members:',
    'mssv': 'Student ID',
  },
};
